#!/usr/bin/env python3
"""gen_features.py — generate the [features] block of mcpp.toml (M8).

One feature per Boost library. Each feature's `sources` = that library's
`.cppm` plus (for compiled libraries) its `libs/*/src/**` TU globs; `implies` =
the library's module import edges (read from src/gen_exports/<lib>.deps). The
generator also keeps `[build].sources` (the union of every feature's globs) in
sync — both are spliced between markers, so they cannot drift.

Why base keeps every per-lib glob: `mcpp test` (includeDevDeps) skips the DROP
(only ADD runs), so the base `[build].sources` is what test mode compiles. If
per-lib globs lived ONLY in features, the default `mcpp test` would not build
the opt-in libraries and their tests would fail (plan §1.8 describes exactly
this feature-only shape; M8 keeps the base globs so the full 27-lib test suite
is green by default, and `--features all` / per-group runs remain additive).
`mcpp build` (build mode) runs the DROP, so only active features' globs compile
— that is where the default-features selection actually takes effect. See
.agents/docs/2026-08-15-m8-mcpp-features-infra.md §1.1/§2.

Usage:
    uv run python scripts/gen_features.py          # splice mcpp.toml + features.lst
    uv run python scripts/gen_features.py --check  # verify committed output is current
"""

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MCPP_TOML = ROOT / "mcpp.toml"
LIBS_JSON = ROOT / "scripts" / "libs.json"
DEPS_DIR = ROOT / "src" / "gen_exports"
FEATURES_LST = ROOT / "scripts" / "features.lst"

# The full module-library list — derived from boost_common.TARGET_LIBS (which
# knows the tier tables). boost_common has no hard dependency on libclang at
# import time, so plain `uv run python scripts/gen_features.py` works.
sys.path.insert(0, str(ROOT / "scripts"))
try:
    import boost_common as bc
    LIBS = list(bc.TARGET_LIBS)
except Exception:
    LIBS = [
        "optional", "variant", "variant2", "any", "core", "container_hash",
        "mp11", "static_string", "scope", "scope_exit", "type_traits",
        "algorithm", "iterator", "range", "io", "rational", "endian",
        "tuple", "system",
        "filesystem", "regex", "thread", "chrono", "program_options",
        "stacktrace", "json", "url",
    ]

# Default feature set = 18-lib closure (plan §3.2). The closure is computed from
# .deps below and asserted to be closed before writing; this is the candidate list.
DEFAULT_CANDIDATES = [
    "any", "algorithm", "chrono", "core", "filesystem", "io", "iterator",
    "json", "mp11", "optional", "range", "regex", "system", "thread",
    "tuple", "type_traits", "variant", "variant2",
]

# Compiled libraries: feature sources = .cppm + these TU globs.
COMPILED_TU_GLOBS = {
    "filesystem":       ["deps/boost/libs/filesystem/src/*.cpp"],
    "regex":            ["deps/boost/libs/regex/src/*.cpp"],
    "chrono":           ["deps/boost/libs/chrono/src/*.cpp"],
    "program_options":  ["deps/boost/libs/program_options/src/*.cpp"],
    "stacktrace":       ["deps/boost/libs/stacktrace/src/basic.cpp"],
    "json":             ["deps/boost/libs/json/src/*.cpp"],
    "url":              ["deps/boost/libs/url/src/**/*.cpp"],
    # thread: all-platform globs live in the feature; the target tables below
    # `!`-exclude the cross-platform ones (plan §3.1 "per-OS TU 互斥").
    "thread":           ["deps/boost/libs/thread/src/future.cpp",
                         "deps/boost/libs/thread/src/win32/*.cpp",
                         "deps/boost/libs/thread/src/pthread/once.cpp",
                         "deps/boost/libs/thread/src/pthread/thread.cpp"],
    # M9: parser pulls boost/charconv when std::from_chars is unavailable
    # (detail/numeric.hpp picks boost_charconv branch; seen on the linux-llvm
    # CI leg). boost.charconv is a compiled lib — ship its TUs with the parser
    # feature so the module's consumers link. On platforms where the std
    # branch is active the TUs compile but produce no referenced symbols.
    "parser":           ["deps/boost/libs/charconv/src/*.cpp"],
}

# Per-lib private compile flags (feature `flags` = private per-TU, never
# propagated to consumers — plan §3.1; was [build].flags in M4).
FEATURE_FLAGS = {
    "thread": [{"glob": "deps/boost/libs/thread/src/**",
                "defines": ["BOOST_THREAD_BUILD_LIB"]}],
}

# Library-owned extras (non-module TU needed by the module, M5/M7).
EXTRAS = {
    "system": ["src/boost_system_extras.cpp"],
    "thread": ["src/boost_thread_extras.cpp"],
}

# Base `[build].flags` / ldflags that no longer live in features.
BASE_LDFLAGS_UNIX = ["-pthread"]

GEN_START = "# ── <gen-features> generated by scripts/gen_features.py — do not edit ──"
GEN_END = "# ── </gen-features> ──"


def load_libs_json():
    if LIBS_JSON.exists():
        return json.loads(LIBS_JSON.read_text(encoding="utf-8"))
    return None


def deps_of(lib):
    """Module import edges for a lib: {home lib} from src/gen_exports/<lib>.deps."""
    p = DEPS_DIR / (lib + ".deps")
    if not p.exists():
        return set()
    return {line.strip()[len("boost."):]
            for line in p.read_text(encoding="utf-8").splitlines()
            if line.strip().startswith("boost.")}


def feature_sources(lib):
    srcs = ["src/{}.cppm".format(lib)]
    srcs.extend(COMPILED_TU_GLOBS.get(lib, ()))
    srcs.extend(EXTRAS.get(lib, ()))
    return srcs


def all_sources():
    """Union of every feature's sources = [build].sources."""
    seen, out = set(), []
    for lib in LIBS:
        for g in feature_sources(lib):
            if g not in seen:
                seen.add(g)
                out.append(g)
    return out


def default_closure(candidates):
    """Candidates + their implies closure (within the full lib set)."""
    graph = {lib: deps_of(lib) for lib in LIBS}
    active = set(candidates)
    changed = True
    while changed:
        changed = False
        for lib in list(active):
            for dep in graph[lib]:
                if dep not in active:
                    active.add(dep)
                    changed = True
    return [lib for lib in LIBS if lib in active]


def assert_closed(closure):
    graph = {lib: deps_of(lib) for lib in LIBS}
    missing = sorted({d for lib in closure for d in graph[lib]} - set(closure))
    if missing:
        raise SystemExit(
            "default closure not closed; missing implies: {}".format(missing))


def _flags_toml(flags):
    return "[{}]".format(", ".join(
        '{{ glob = "{}", defines = [{}] }}'.format(
            f["glob"], ", ".join('"{}"'.format(d) for d in f["defines"]))
        for f in flags))


def render_toml_block():
    closure = default_closure(DEFAULT_CANDIDATES)
    assert_closed(closure)
    optin = [lib for lib in LIBS if lib not in closure]

    lines = [GEN_START]
    lines.append("[features]")
    lines.append("default = [{}]".format(", ".join('"{}"'.format(l) for l in closure)))
    lines.append("all = {{ implies = [{}] }}".format(
        ", ".join('"{}"'.format(l) for l in LIBS)))
    for lib in LIBS:
        lines.append("[features.{}]".format(lib))
        lines.append("  sources = [{}]".format(
            ", ".join('"{}"'.format(s) for s in feature_sources(lib))))
        if lib in FEATURE_FLAGS:
            lines.append("  flags = {}".format(_flags_toml(FEATURE_FLAGS[lib])))
        deps = sorted(deps_of(lib))
        if deps:
            lines.append("  implies = [{}]".format(
                ", ".join('"{}"'.format(d) for d in deps)))
    lines.append(GEN_END)
    return "\n".join(lines) + "\n"


def render_sources_block():
    srcs = all_sources()
    return ("# ── <gen-sources> generated by scripts/gen_features.py — do not edit ──\n"
            "sources = [\n"
            + "\n".join('    "{}",'.format(s) for s in srcs)
            + "\n]\n"
            + "# ── </gen-sources> ──\n")


def splice(text, start_marker, end_marker, replacement):
    start = text.find(start_marker)
    end = text.find(end_marker)
    if start == -1 or end == -1 or end <= start:
        raise SystemExit("markers not found in mcpp.toml: {} / {}".format(
            start_marker, end_marker))
    end = text.find("\n", end) + 1
    return text[:start] + replacement + text[end:]


def write_committed():
    text = MCPP_TOML.read_text(encoding="utf-8")
    text = splice(text, "# ── <gen-sources>", "# ── </gen-sources>",
                  render_sources_block())
    text = splice(text, GEN_START, GEN_END, render_toml_block())
    MCPP_TOML.write_text(text, encoding="utf-8", newline="\n")
    FEATURES_LST.write_text("\n".join(LIBS) + "\n", encoding="utf-8", newline="\n")
    closure = default_closure(DEFAULT_CANDIDATES)
    print("wrote {}{} with {} features; default={} opt-in={}".format(
        MCPP_TOML, "" , len(LIBS), ",".join(closure),
        ",".join(l for l in LIBS if l not in closure)))
    print("wrote {} ({} libs)".format(FEATURES_LST, len(LIBS)))
    print("default closure: {}".format(" ".join(closure)))
    print("opt-in: {}".format(" ".join(l for l in LIBS if l not in closure)))


def check_committed():
    text = MCPP_TOML.read_text(encoding="utf-8")
    ok = True
    for name, marker_start, marker_end, expected in (
            ("sources", "# ── <gen-sources>", "# ── </gen-sources>",
             render_sources_block()),
            ("features", GEN_START, GEN_END, render_toml_block())):
        s = text.find(marker_start)
        e = text.find(marker_end)
        if s == -1 or e == -1:
            print("MISSING {} markers".format(name))
            ok = False
            continue
        e = text.find("\n", e) + 1
        actual = text[s:e]
        if actual != expected:
            print("DRIFT in {} block: run scripts/gen_features.py".format(name))
            ok = False
    lst = FEATURES_LST.read_text(encoding="utf-8").splitlines() if FEATURES_LST.exists() else []
    if lst != LIBS:
        print("DRIFT in features.lst")
        ok = False
    return ok


def main():
    if len(sys.argv) > 1 and sys.argv[1] == "--check":
        sys.exit(0 if check_committed() else 1)
    write_committed()
    return 0


if __name__ == "__main__":
    main()
