// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/accumulators/statistics.hpp>
#include <boost/accumulators/statistics/p_square_cumulative_distribution.hpp>
#include <boost/accumulators/statistics/rolling_variance.hpp>
#include <boost/accumulators/statistics/weighted_p_square_cumulative_distribution.hpp>

export module boost.accumulators;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.numeric;
export import boost.type_traits;
export import boost.utility;

#include "gen_exports/accumulators.inc"

