// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/align.hpp>

export module boost.align;

export import boost.assert;
export import boost.config;
export import boost.core;

#include "gen_exports/align.inc"

