// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/array.hpp>

export module boost.array;

export import boost.assert;
export import boost.config;
export import boost.throw_exception;

#include "gen_exports/array.inc"

