// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/asio.hpp>
#include <boost/asio/deadline_timer.hpp>
#include <boost/asio/experimental/as_single.hpp>
#include <boost/asio/experimental/awaitable_operators.hpp>
#include <boost/asio/experimental/channel.hpp>
#include <boost/asio/experimental/co_composed.hpp>
#include <boost/asio/experimental/co_spawn.hpp>
#include <boost/asio/experimental/concurrent_channel.hpp>
#include <boost/asio/experimental/promise.hpp>
#include <boost/asio/experimental/use_coro.hpp>
#include <boost/asio/spawn.hpp>
#include <boost/asio/ssl/stream_base.hpp>
#include <boost/asio/ts/net.hpp>
#include <boost/asio/unyield.hpp>
#include <boost/asio/yield.hpp>

export module boost.asio;

export import boost.assert;
export import boost.date_time;
export import boost.system;

#include "gen_exports/asio.inc"

