// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/assert.hpp>
#include <boost/assert/source_location.hpp>

export module boost.assert;

export import boost.config;

#include "gen_exports/assert.inc"

