// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/assign.hpp>
#include <boost/assign/ptr_list_inserter.hpp>
#include <boost/assign/ptr_list_of.hpp>
#include <boost/assign/ptr_map_inserter.hpp>

export module boost.assign;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.iterator;
export import boost.move;
export import boost.ptr_container;
export import boost.type_traits;

#include "gen_exports/assign.inc"

