// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/atomic.hpp>

export module boost.atomic;

export import boost.config;

#include "gen_exports/atomic.inc"

