// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/beast.hpp>
#include <boost/beast/_experimental/http/icy_stream.hpp>
#include <boost/beast/_experimental/test/immediate_executor.hpp>
#include <boost/beast/_experimental/test/stream.hpp>
#include <boost/beast/_experimental/test/tcp.hpp>
#include <boost/beast/_experimental/unit_test/dstream.hpp>
#include <boost/beast/_experimental/unit_test/match.hpp>
#include <boost/beast/_experimental/unit_test/reporter.hpp>
#include <boost/beast/core/buffer_ref.hpp>
#include <boost/beast/core/string_param.hpp>

export module boost.beast;

export import boost.asio;
export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.logic;
export import boost.optional;
export import boost.smart_ptr;
export import boost.system;
export import boost.throw_exception;
export import boost.type_index;
export import boost.winapi;

#include "gen_exports/beast.inc"

