// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/bimap.hpp>
#include <boost/bimap/container_adaptor/support/iterator_facade_converters.hpp>
#include <boost/bimap/list_of.hpp>
#include <boost/bimap/multiset_of.hpp>
#include <boost/bimap/property_map/set_support.hpp>
#include <boost/bimap/property_map/unordered_set_support.hpp>
#include <boost/bimap/relation/mutant_relation.hpp>
#include <boost/bimap/relation/support/get_pair_functor.hpp>
#include <boost/bimap/relation/support/is_tag_of_member_at.hpp>
#include <boost/bimap/relation/support/opposite_tag.hpp>
#include <boost/bimap/support/lambda.hpp>
#include <boost/bimap/support/value_type_by.hpp>
#include <boost/bimap/tags/support/apply_to_value_type.hpp>
#include <boost/bimap/tags/support/is_tagged.hpp>
#include <boost/bimap/tags/support/overwrite_tagged.hpp>
#include <boost/bimap/unconstrained_set_of.hpp>
#include <boost/bimap/unordered_multiset_of.hpp>
#include <boost/bimap/vector_of.hpp>

export module boost.bimap;

export import boost.assert;
export import boost.concept_check;
export import boost.config;
export import boost.core;
export import boost.functional;
export import boost.iterator;
export import boost.multi_index;
export import boost.tuple;
export import boost.type_traits;
export import boost.utility;

#include "gen_exports/bimap.inc"

