// GENERATED by scripts/gen_exports.py - DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/bind.hpp>
#include <boost/bind/apply.hpp>
#include <boost/bind/make_adaptable.hpp>
#include <boost/bind/protect.hpp>

export module boost.bind;

export import boost.config;
export import boost.core;

#include "gen_exports/bind.inc"

