// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/bloom.hpp>

export module boost.bloom;

export import boost.assert;
export import boost.core;

#include "gen_exports/bloom.inc"

