// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/callable_traits.hpp>
#include <boost/callable_traits/is_cv_member.hpp>

export module boost.callable_traits;

#include "gen_exports/callable_traits.inc"

