// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/chrono.hpp>
#include <boost/chrono/typeof/boost/chrono/chrono.hpp>
#include <boost/chrono/typeof/boost/ratio.hpp>

export module boost.chrono;

export import boost.assert;
export import boost.config;
export import boost.ratio;
export import boost.system;
export import boost.type_traits;

#include "gen_exports/chrono.inc"

