// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/circular_buffer.hpp>

export module boost.circular_buffer;

export import boost.assert;
export import boost.config;
export import boost.type_traits;

#include "gen_exports/circular_buffer.inc"

