// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/cobalt.hpp>
// M11 platform guard (POSIX): asio reactor/hash_map details were only
// reached through windows-flavored chains in the mingw snapshot (POSIX
// cobalt selects the epoll reactor); include them explicitly so the
// shared-surface `using` lines resolve.
#include <boost/asio/detail/hash_map.hpp>
#include <boost/asio/detail/null_reactor.hpp>
#include <boost/asio/detail/select_reactor.hpp>
// fd_set_adapter / reactor_op_queue / socket_select_interrupter are
// per-OS-selected headers with no outer platform guard; the reactor
// headers above self-guard empty on the epoll/kqueue paths (their
// entities are guarded _WIN32 in the .inc instead).
#include <boost/asio/detail/fd_set_adapter.hpp>
#include <boost/asio/detail/reactor_op_queue.hpp>
#include <boost/asio/detail/socket_select_interrupter.hpp>
#include <boost/cobalt/composition.hpp>
#include <boost/cobalt/experimental/context.hpp>
#include <boost/cobalt/experimental/yield_context.hpp>
#include <boost/cobalt/io.hpp>

export module boost.cobalt;

export import boost.asio;
export import boost.assert;
export import boost.callable_traits;
export import boost.config;
export import boost.core;
export import boost.intrusive;
export import boost.mp11;
export import boost.smart_ptr;
export import boost.system;
export import boost.variant2;

#include "gen_exports/cobalt.inc"

