// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/compat/bind_back.hpp>
#include <boost/compat/bind_front.hpp>
#include <boost/compat/function_ref.hpp>
#include <boost/compat/latch.hpp>
#include <boost/compat/move_only_function.hpp>
#include <boost/compat/shared_lock.hpp>
#include <boost/compat/to_array.hpp>
#include <boost/compat/to_underlying.hpp>

export module boost.compat;

export import boost.assert;
export import boost.config;

#include "gen_exports/compat.inc"

