// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/concept_check.hpp>
#include <boost/concept_check/borland.hpp>
#include <boost/concept_check/general.hpp>

export module boost.concept_check;

export import boost.config;
export import boost.type_traits;

#include "gen_exports/concept_check.inc"

