// GENERATED by scripts/gen_exports.py - DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/container/adaptive_pool.hpp>
#include <boost/container/allocator.hpp>
#include <boost/container/experimental/pmr/nest.hpp>
#include <boost/container/experimental/segmented_all_of.hpp>
#include <boost/container/experimental/segmented_any_of.hpp>
#include <boost/container/experimental/segmented_copy_if.hpp>
#include <boost/container/experimental/segmented_copy_n.hpp>
#include <boost/container/experimental/segmented_count.hpp>
#include <boost/container/experimental/segmented_count_if.hpp>
#include <boost/container/experimental/segmented_equal.hpp>
#include <boost/container/experimental/segmented_fill.hpp>
#include <boost/container/experimental/segmented_find_last.hpp>
#include <boost/container/experimental/segmented_find_last_if_not.hpp>
#include <boost/container/experimental/segmented_for_each.hpp>
#include <boost/container/experimental/segmented_generate.hpp>
#include <boost/container/experimental/segmented_generate_n.hpp>
#include <boost/container/experimental/segmented_is_partitioned.hpp>
#include <boost/container/experimental/segmented_is_sorted.hpp>
#include <boost/container/experimental/segmented_merge.hpp>
#include <boost/container/experimental/segmented_partition.hpp>
#include <boost/container/experimental/segmented_partition_copy.hpp>
#include <boost/container/experimental/segmented_partition_point.hpp>
#include <boost/container/experimental/segmented_remove.hpp>
#include <boost/container/experimental/segmented_remove_if.hpp>
#include <boost/container/experimental/segmented_replace.hpp>
#include <boost/container/experimental/segmented_replace_if.hpp>
#include <boost/container/experimental/segmented_reverse.hpp>
#include <boost/container/experimental/segmented_reverse_copy.hpp>
#include <boost/container/experimental/segmented_search.hpp>
#include <boost/container/experimental/segmented_search_n.hpp>
#include <boost/container/experimental/segmented_set_difference.hpp>
#include <boost/container/experimental/segmented_set_intersection.hpp>
#include <boost/container/experimental/segmented_set_symmetric_difference.hpp>
#include <boost/container/experimental/segmented_set_union.hpp>
#include <boost/container/experimental/segmented_stable_partition.hpp>
#include <boost/container/experimental/segmented_swap_ranges.hpp>
#include <boost/container/experimental/segmented_transform.hpp>
#include <boost/container/experimental/wrapped_iterator.hpp>
#include <boost/container/node_handle.hpp>
#include <boost/container/pmr/deque.hpp>
#include <boost/container/pmr/devector.hpp>
#include <boost/container/pmr/flat_map.hpp>
#include <boost/container/pmr/flat_set.hpp>
#include <boost/container/pmr/hub.hpp>
#include <boost/container/pmr/list.hpp>
#include <boost/container/pmr/map.hpp>
#include <boost/container/pmr/monotonic_buffer_resource.hpp>
#include <boost/container/pmr/pool_options.hpp>
#include <boost/container/pmr/resource_adaptor.hpp>
#include <boost/container/pmr/segtor.hpp>
#include <boost/container/pmr/set.hpp>
#include <boost/container/pmr/slist.hpp>
#include <boost/container/pmr/small_vector.hpp>
#include <boost/container/pmr/stable_vector.hpp>
#include <boost/container/pmr/string.hpp>
#include <boost/container/pmr/synchronized_pool_resource.hpp>
#include <boost/container/pmr/unsynchronized_pool_resource.hpp>
#include <boost/container/pmr/vector.hpp>
#include <boost/container/scoped_allocator.hpp>
#include <boost/container/static_vector.hpp>
#include <boost/container/uses_allocator.hpp>
#include <boost/container/uses_allocator_construction.hpp>

export module boost.container;

export import boost.assert;
export import boost.config;
export import boost.intrusive;
export import boost.move;

#include "gen_exports/container.inc"

