// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/container/adaptive_pool.hpp>
#include <boost/container/allocator.hpp>
#include <boost/container/experimental/pmr/nest.hpp>
#include <boost/container/node_handle.hpp>
#include <boost/container/pmr/deque.hpp>
#include <boost/container/pmr/devector.hpp>
#include <boost/container/pmr/flat_map.hpp>
#include <boost/container/pmr/flat_set.hpp>
#include <boost/container/pmr/list.hpp>
#include <boost/container/pmr/map.hpp>
#include <boost/container/pmr/monotonic_buffer_resource.hpp>
#include <boost/container/pmr/pool_options.hpp>
#include <boost/container/pmr/resource_adaptor.hpp>
#include <boost/container/pmr/segtor.hpp>
#include <boost/container/pmr/set.hpp>
#include <boost/container/pmr/slist.hpp>
#include <boost/container/pmr/small_vector.hpp>
#include <boost/container/pmr/stable_vector.hpp>
#include <boost/container/pmr/string.hpp>
#include <boost/container/pmr/synchronized_pool_resource.hpp>
#include <boost/container/pmr/unsynchronized_pool_resource.hpp>
#include <boost/container/pmr/vector.hpp>
#include <boost/container/scoped_allocator.hpp>
#include <boost/container/static_vector.hpp>
#include <boost/container/uses_allocator.hpp>
#include <boost/container/uses_allocator_construction.hpp>

export module boost.container;

export import boost.assert;
export import boost.config;
export import boost.intrusive;
export import boost.move;

#include "gen_exports/container.inc"

