// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/decimal.hpp>
#include <boost/decimal/fmt_format.hpp>

export module boost.decimal;

#include "gen_exports/decimal.inc"

