// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/dll.hpp>
#include <boost/dll/import_class.hpp>
#include <boost/dll/shared_library_load_mode.hpp>

export module boost.dll;

export import boost.assert;
export import boost.core;
export import boost.filesystem;
export import boost.winapi;

#include "gen_exports/dll.inc"

