// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/dynamic_bitset.hpp>
#include <boost/dynamic_bitset/serialization.hpp>

export module boost.dynamic_bitset;

export import boost.assert;
export import boost.core;

#include "gen_exports/dynamic_bitset.inc"

