// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/filesystem.hpp>
#include <boost/filesystem/cstdio.hpp>
#include <boost/filesystem/fstream.hpp>

export module boost.filesystem;

export import boost.system;

#include "gen_exports/filesystem.inc"

