// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/flyweight.hpp>
#include <boost/flyweight/concurrent_factory.hpp>
#include <boost/flyweight/intermodule_holder.hpp>
#include <boost/flyweight/key_value.hpp>
#include <boost/flyweight/no_locking.hpp>
#include <boost/flyweight/no_tracking.hpp>
#include <boost/flyweight/serialize.hpp>
#include <boost/flyweight/set_factory.hpp>

export module boost.flyweight;

export import boost.assert;
export import boost.config;
export import boost.container;
export import boost.core;
export import boost.intrusive;
export import boost.move;
export import boost.mp11;
export import boost.multi_index;
export import boost.smart_ptr;
export import boost.throw_exception;
export import boost.type_traits;
export import boost.unordered;
export import boost.winapi;

#include "gen_exports/flyweight.inc"

