// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/format.hpp>

export module boost.format;

export import boost.assert;
export import boost.config;

#include "gen_exports/format.inc"

