// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/gil/extension/dynamic_image/dynamic_at_c.hpp>
#include <boost/gil/extension/histogram/std.hpp>
#include <boost/gil/extension/io/bmp/old.hpp>
#include <boost/gil/extension/io/pnm/old.hpp>
#include <boost/gil/extension/io/targa/old.hpp>
#include <boost/gil/extension/numeric/algorithm.hpp>
#include <boost/gil/extension/numeric/channel_numeric_operations.hpp>
#include <boost/gil/extension/numeric/convolve.hpp>
#include <boost/gil/extension/numeric/kernel.hpp>
#include <boost/gil/extension/numeric/pixel_numeric_operations.hpp>
#include <boost/gil/extension/numeric/resample.hpp>
#include <boost/gil/extension/numeric/sampler.hpp>
#include <boost/gil/extension/toolbox/color_spaces/ycbcr.hpp>
#include <boost/gil/extension/toolbox/image_types/subchroma_image.hpp>
#include <boost/gil/io/bit_operations.hpp>
#include <boost/gil/io/io.hpp>
#include <boost/gil/io/reader_base.hpp>
#include <boost/gil/io/row_buffer_helper.hpp>

export module boost.gil;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.iterator;
export import boost.mp11;
export import boost.variant2;

#include "gen_exports/gil.inc"

