// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/hana.hpp>
#include <boost/hana/experimental/printable.hpp>
#include <boost/hana/experimental/type_name.hpp>
#include <boost/hana/experimental/types.hpp>
#include <boost/hana/experimental/view.hpp>
#include <boost/hana/ext/boost.hpp>
#include <boost/hana/ext/std.hpp>
#include <boost/hana/fwd/core.hpp>

export module boost.hana;

export import boost.core;
export import boost.type_traits;

#include "gen_exports/hana.inc"

