// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/heap/binomial_heap.hpp>
#include <boost/heap/d_ary_heap.hpp>
#include <boost/heap/fibonacci_heap.hpp>
#include <boost/heap/heap_merge.hpp>
#include <boost/heap/pairing_heap.hpp>
#include <boost/heap/priority_queue.hpp>
#include <boost/heap/skew_heap.hpp>

export module boost.heap;

export import boost.assert;
export import boost.concept_check;
export import boost.config;
export import boost.core;
export import boost.intrusive;
export import boost.iterator;
export import boost.mp11;
export import boost.type_traits;

// M9: heap's container templates (d_ary_heap etc.) instantiate the intrusive
// placement new (`::new(p, boost_move_new_t()) T`) in the consumer TU, where
// the global operator new overload from move/detail/placement_new.hpp (a GMF
// include) is not visible. M0 rule: re-export the global operator new
// overloads from the module purview.
export using ::operator new;

#include "gen_exports/heap.inc"

