// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/hof.hpp>
#include <boost/hof/version.hpp>

export module boost.hof;

#include "gen_exports/hof.inc"

