// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/icl/concept/interval_set_value.hpp>
#include <boost/icl/gregorian.hpp>
#include <boost/icl/map.hpp>
#include <boost/icl/predicates/distinct_equal.hpp>
#include <boost/icl/predicates/element_equal.hpp>
#include <boost/icl/predicates/std_equal.hpp>
#include <boost/icl/predicates/sub_super_set.hpp>
#include <boost/icl/ptime.hpp>
#include <boost/icl/rational.hpp>
#include <boost/icl/separate_interval_set.hpp>
#include <boost/icl/set.hpp>
#include <boost/icl/split_interval_map.hpp>
#include <boost/icl/type_traits/adds_inversely.hpp>
#include <boost/icl/type_traits/difference.hpp>

export module boost.icl;

export import boost.assert;
export import boost.config;
export import boost.container;
export import boost.date_time;
export import boost.io;
export import boost.iterator;
export import boost.rational;
export import boost.type_traits;
export import boost.utility;

#include "gen_exports/icl.inc"

