// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/integer/common_factor.hpp>
#include <boost/integer/integer_log2.hpp>
#include <boost/integer/integer_mask.hpp>
#include <boost/integer/mod_inverse.hpp>
#include <boost/integer/static_log2.hpp>
#include <boost/integer/static_min_max.hpp>

export module boost.integer;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.throw_exception;
export import boost.type_traits;

#include "gen_exports/integer.inc"

