// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/io/nullstream.hpp>
#include <boost/io/ostream_joiner.hpp>
#include <boost/io/ostream_put.hpp>
#include <boost/io/quoted.hpp>

export module boost.io;

#include "gen_exports/io.inc"

