// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/json/debug_printers.hpp>
#include <boost/json/src.hpp>

export module boost.json;

export import boost.core;
export import boost.mp11;
export import boost.system;
export import boost.variant2;

#include "gen_exports/json.inc"

