// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/lambda/algorithm.hpp>
#include <boost/lambda/bind.hpp>
#include <boost/lambda/casts.hpp>
#include <boost/lambda/closures.hpp>
#include <boost/lambda/construct.hpp>
#include <boost/lambda/control_structures.hpp>
#include <boost/lambda/exceptions.hpp>
#include <boost/lambda/lambda.hpp>
#include <boost/lambda/numeric.hpp>
#include <boost/lambda/switch.hpp>

export module boost.lambda;

export import boost.config;
export import boost.tuple;
export import boost.type_traits;

#include "gen_exports/lambda.inc"

