// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/leaf.hpp>
#include <boost/leaf/common.hpp>
#include <boost/leaf/diagnostics.hpp>
#include <boost/leaf/on_error.hpp>
#include <boost/leaf/pred.hpp>
#include <boost/leaf/serialization/boost_json_encoder.hpp>
#include <boost/leaf/serialization/nlohmann_json_encoder.hpp>
#include <boost/leaf/to_variant.hpp>

export module boost.leaf;

#include "gen_exports/leaf.inc"

