// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/lexical_cast.hpp>

export module boost.lexical_cast;

export import boost.assert;
export import boost.config;
export import boost.core;

#include "gen_exports/lexical_cast.inc"

