// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/log/attributes.hpp>
#include <boost/log/common.hpp>
#include <boost/log/expressions.hpp>
#include <boost/log/sinks.hpp>
#include <boost/log/sources/logger.hpp>
#include <boost/log/support/date_time.hpp>
#include <boost/log/support/exception.hpp>
#include <boost/log/support/regex.hpp>
#include <boost/log/support/spirit_classic.hpp>
#include <boost/log/support/spirit_qi.hpp>
#include <boost/log/support/std_regex.hpp>
#include <boost/log/support/xpressive.hpp>
#include <boost/log/trivial.hpp>
#include <boost/log/utility/exception_handler.hpp>
#include <boost/log/utility/functional.hpp>
#include <boost/log/utility/ipc/reliable_message_queue.hpp>
#include <boost/log/utility/manipulators.hpp>
#include <boost/log/utility/manipulators/invoke.hpp>
#include <boost/log/utility/manipulators/optional.hpp>
#include <boost/log/utility/manipulators/range.hpp>
#include <boost/log/utility/manipulators/tuple.hpp>
#include <boost/log/utility/record_ordering.hpp>
#include <boost/log/utility/setup.hpp>
#include <boost/log/utility/type_dispatch/date_time_types.hpp>
#include <boost/log/utility/type_dispatch/dynamic_type_dispatcher.hpp>
#include <boost/log/utility/type_dispatch/standard_types.hpp>

export module boost.log;

export import boost.assert;
export import boost.atomic;
export import boost.config;
export import boost.core;
export import boost.date_time;
export import boost.filesystem;
export import boost.integer;
export import boost.intrusive;
export import boost.io;
export import boost.iterator;
export import boost.move;
export import boost.mp11;
export import boost.optional;
export import boost.property_tree;
export import boost.range;
export import boost.regex;
export import boost.smart_ptr;
export import boost.system;
export import boost.thread;
export import boost.throw_exception;
export import boost.type_index;
export import boost.type_traits;
export import boost.utility;
export import boost.variant;
export import boost.winapi;

#include "gen_exports/log.inc"

