// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/logic/tribool_io.hpp>

export module boost.logic;

export import boost.config;
export import boost.core;

#include "gen_exports/logic.inc"

