// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/math/ccmath/ccmath.hpp>
#include <boost/math/common_factor.hpp>
#include <boost/math/complex.hpp>
#include <boost/math/concepts/distributions.hpp>
#include <boost/math/concepts/real_concept.hpp>
#include <boost/math/concepts/real_type_concept.hpp>
#include <boost/math/concepts/std_real_concept.hpp>
#include <boost/math/constants/info.hpp>
#include <boost/math/cstdfloat/cstdfloat_complex.hpp>
#include <boost/math/differentiation/autodiff.hpp>
#include <boost/math/differentiation/lanczos_smoothing.hpp>
#include <boost/math/distributions.hpp>
#include <boost/math/distributions/empirical_cumulative_distribution_function.hpp>
#include <boost/math/interpolators/barycentric_rational.hpp>
#include <boost/math/interpolators/bezier_polynomial.hpp>
#include <boost/math/interpolators/bilinear_uniform.hpp>
#include <boost/math/interpolators/cardinal_cubic_b_spline.hpp>
#include <boost/math/interpolators/cardinal_quadratic_b_spline.hpp>
#include <boost/math/interpolators/cardinal_quintic_b_spline.hpp>
#include <boost/math/interpolators/catmull_rom.hpp>
#include <boost/math/interpolators/cubic_b_spline.hpp>
#include <boost/math/interpolators/cubic_hermite.hpp>
#include <boost/math/interpolators/makima.hpp>
#include <boost/math/interpolators/pchip.hpp>
#include <boost/math/interpolators/quintic_hermite.hpp>
#include <boost/math/interpolators/septic_hermite.hpp>
#include <boost/math/interpolators/vector_barycentric_rational.hpp>
#include <boost/math/interpolators/whittaker_shannon.hpp>
#include <boost/math/octonion.hpp>
#include <boost/math/optimization/differential_evolution.hpp>
#include <boost/math/optimization/jso.hpp>
#include <boost/math/optimization/minimizer.hpp>
#include <boost/math/optimization/random_search.hpp>
#include <boost/math/quadrature/gauss_kronrod.hpp>
#include <boost/math/quadrature/naive_monte_carlo.hpp>
#include <boost/math/quadrature/ooura_fourier_integrals.hpp>
#include <boost/math/quadrature/sinh_sinh.hpp>
#include <boost/math/quadrature/tanh_sinh.hpp>
#include <boost/math/quadrature/wavelet_transforms.hpp>
#include <boost/math/special_functions.hpp>
#include <boost/math/special_functions/bessel_iterators.hpp>
#include <boost/math/special_functions/cardinal_b_spline.hpp>
#include <boost/math/special_functions/fibonacci.hpp>
#include <boost/math/special_functions/fourier_transform_daubechies.hpp>
#include <boost/math/special_functions/logsumexp.hpp>
#include <boost/math/special_functions/nonfinite_num_facets.hpp>
#include <boost/math/special_functions/prime.hpp>
#include <boost/math/special_functions/rsqrt.hpp>
#include <boost/math/statistics/anderson_darling.hpp>
#include <boost/math/statistics/chatterjee_correlation.hpp>
#include <boost/math/statistics/linear_regression.hpp>
#include <boost/math/statistics/ljung_box.hpp>
#include <boost/math/statistics/runs_test.hpp>
#include <boost/math/statistics/signal_statistics.hpp>
#include <boost/math/statistics/t_test.hpp>
#include <boost/math/statistics/z_test.hpp>
#include <boost/math/tools/agm.hpp>
#include <boost/math/tools/array.hpp>
#include <boost/math/tools/atomic.hpp>
#include <boost/math/tools/bivariate_statistics.hpp>
#include <boost/math/tools/centered_continued_fraction.hpp>
#include <boost/math/tools/cohen_acceleration.hpp>
#include <boost/math/tools/color_maps.hpp>
#include <boost/math/tools/concepts.hpp>
#include <boost/math/tools/engel_expansion.hpp>
#include <boost/math/tools/luroth_expansion.hpp>
#include <boost/math/tools/norms.hpp>
#include <boost/math/tools/numerical_differentiation.hpp>
#include <boost/math/tools/polynomial.hpp>
#include <boost/math/tools/quartic_roots.hpp>
#include <boost/math/tools/random_vector.hpp>
#include <boost/math/tools/simple_continued_fraction.hpp>
#include <boost/math/tools/stats.hpp>
#include <boost/math/tools/test_value.hpp>
#include <boost/math/tools/ulps_plot.hpp>
#include <boost/math/tools/univariate_statistics.hpp>
#include <boost/math/tr1.hpp>

export module boost.math;

export import boost.assert;
export import boost.concept_check;
export import boost.config;
export import boost.core;
export import boost.lexical_cast;
export import boost.random;

#include "gen_exports/math.inc"

