// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/move/algo/adaptive_merge.hpp>
#include <boost/move/algo/adaptive_sort.hpp>
#include <boost/move/algo/predicate.hpp>
#include <boost/move/algo/unique.hpp>
#include <boost/move/make_unique.hpp>
#include <boost/move/move.hpp>

export module boost.move;

export import boost.config;

#include "gen_exports/move.inc"

