// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/mp11.hpp>
#include <boost/mp11/mpl.hpp>

export module boost.mp11;

#include "gen_exports/mp11.inc"

