// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/mqtt5.hpp>
#include <boost/mqtt5/websocket.hpp>

export module boost.mqtt5;

export import boost.asio;
export import boost.assert;
export import boost.beast;
export import boost.container;
export import boost.core;
export import boost.random;
export import boost.smart_ptr;
export import boost.static_string;
export import boost.system;

#include "gen_exports/mqtt5.inc"

