// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/multi_array.hpp>

export module boost.multi_array;

export import boost.array;
export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.type_traits;

#include "gen_exports/multi_array.inc"

