// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/multi_index/hashed_index.hpp>
#include <boost/multi_index/key.hpp>
#include <boost/multi_index/key_extractors.hpp>
#include <boost/multi_index/ordered_index.hpp>
#include <boost/multi_index/random_access_index.hpp>
#include <boost/multi_index/ranked_index.hpp>
#include <boost/multi_index/safe_mode_errors.hpp>
#include <boost/multi_index/sequenced_index.hpp>
#include <boost/multi_index_container.hpp>

export module boost.multi_index;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.mp11;
export import boost.throw_exception;
export import boost.tuple;
export import boost.type_traits;
export import boost.utility;

#include "gen_exports/multi_index.inc"

