// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/numeric/conversion/bounds.hpp>
#include <boost/numeric/conversion/cast.hpp>
#include <boost/numeric/conversion/int_float_mixture.hpp>
#include <boost/numeric/conversion/int_float_mixture_enum.hpp>
#include <boost/numeric/conversion/is_subranged.hpp>
#include <boost/numeric/conversion/sign_mixture.hpp>
#include <boost/numeric/conversion/sign_mixture_enum.hpp>
#include <boost/numeric/conversion/udt_builtin_mixture.hpp>
#include <boost/numeric/conversion/udt_builtin_mixture_enum.hpp>
#include <boost/numeric/interval/ext/integer.hpp>
#include <boost/numeric/interval/io.hpp>
#include <boost/numeric/interval/limits.hpp>
#include <boost/numeric/odeint.hpp>
#include <boost/numeric/odeint/algebra/fusion_algebra_dispatcher.hpp>
#include <boost/numeric/odeint/external/openmp/openmp_nested_algebra.hpp>
#include <boost/numeric/odeint/external/openmp/openmp_range_algebra.hpp>
#include <boost/numeric/odeint/iterator/integrate/integrate.hpp>
#include <boost/numeric/odeint/iterator/integrate/integrate_const.hpp>
#include <boost/numeric/odeint/iterator/integrate/integrate_n_steps.hpp>
#include <boost/numeric/odeint/iterator/integrate/integrate_times.hpp>
#include <boost/numeric/odeint/iterator/integrate/observer_collection.hpp>
#include <boost/numeric/odeint/iterator/n_step_iterator.hpp>
#include <boost/numeric/odeint/iterator/n_step_time_iterator.hpp>
#include <boost/numeric/odeint/iterator/times_iterator.hpp>
#include <boost/numeric/odeint/iterator/times_time_iterator.hpp>
#include <boost/numeric/odeint/tools/traits.hpp>
#include <boost/numeric/odeint/util/split.hpp>
#include <boost/numeric/odeint/util/split_adaptor.hpp>
#include <boost/numeric/ublas/assignment.hpp>
#include <boost/numeric/ublas/banded.hpp>
#include <boost/numeric/ublas/blas.hpp>
#include <boost/numeric/ublas/doxydoc.hpp>
#include <boost/numeric/ublas/experimental/sparse_view.hpp>
#include <boost/numeric/ublas/hermitian.hpp>
#include <boost/numeric/ublas/io.hpp>
#include <boost/numeric/ublas/matrix_vector.hpp>
#include <boost/numeric/ublas/operation_blocked.hpp>
#include <boost/numeric/ublas/operation_sparse.hpp>
#include <boost/numeric/ublas/operations.hpp>
#include <boost/numeric/ublas/symmetric.hpp>
#include <boost/numeric/ublas/tensor.hpp>
#include <boost/numeric/ublas/tensor/algorithms.hpp>
#include <boost/numeric/ublas/tensor/extents.hpp>
#include <boost/numeric/ublas/tensor/functions.hpp>
#include <boost/numeric/ublas/tensor/index.hpp>
#include <boost/numeric/ublas/tensor/multiplication.hpp>
#include <boost/numeric/ublas/tensor/operators_arithmetic.hpp>
#include <boost/numeric/ublas/tensor/operators_comparison.hpp>
#include <boost/numeric/ublas/tensor/ostream.hpp>
#include <boost/numeric/ublas/tensor/storage_traits.hpp>
#include <boost/numeric/ublas/tensor/strides.hpp>
#include <boost/numeric/ublas/tensor/tensor.hpp>
#include <boost/numeric/ublas/traits/c_array.hpp>
#include <boost/numeric/ublas/vector_of_vector.hpp>

export module boost.numeric;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.iterator;
export import boost.range;
export import boost.type_traits;
export import boost.utility;

#include "gen_exports/numeric.inc"

