// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/optional.hpp>
#include <boost/optional/optional_io.hpp>

export module boost.optional;

export import boost.core;
export import boost.type_traits;

#include "gen_exports/optional.inc"

