// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/outcome.hpp>
#include <boost/outcome/bad_access.hpp>
#include <boost/outcome/basic_outcome.hpp>
#include <boost/outcome/basic_result.hpp>
#include <boost/outcome/boost_outcome.hpp>
#include <boost/outcome/boost_result.hpp>
#include <boost/outcome/config.hpp>
#include <boost/outcome/convert.hpp>
#include <boost/outcome/coroutine_support.hpp>
#include <boost/outcome/iostream_support.hpp>
#include <boost/outcome/iostream_support_result.hpp>
#include <boost/outcome/outcome.hpp>
#include <boost/outcome/result.hpp>
#include <boost/outcome/std_outcome.hpp>
#include <boost/outcome/std_result.hpp>
#include <boost/outcome/success_failure.hpp>
#include <boost/outcome/trait.hpp>
#include <boost/outcome/try.hpp>
#include <boost/outcome/utils.hpp>

export module boost.outcome;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.smart_ptr;
export import boost.system;
export import boost.throw_exception;
export import boost.type_traits;

#include "gen_exports/outcome.inc"

