// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/parser/split.hpp>
#include <boost/parser/transform_replace.hpp>

export module boost.parser;

export import boost.assert;

#include "gen_exports/parser.inc"

