// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/poly_collection/algorithm.hpp>
#include <boost/poly_collection/any_collection.hpp>
#include <boost/poly_collection/base_collection.hpp>
#include <boost/poly_collection/exception.hpp>
#include <boost/poly_collection/function_collection.hpp>
#include <boost/poly_collection/variant_collection.hpp>

export module boost.poly_collection;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.iterator;
export import boost.mp11;
export import boost.type_traits;

#include "gen_exports/poly_collection.inc"

