// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/polygon/gtl.hpp>
#include <boost/polygon/interval_concept.hpp>
#include <boost/polygon/interval_data.hpp>
#include <boost/polygon/interval_traits.hpp>
#include <boost/polygon/isotropy.hpp>
#include <boost/polygon/point_concept.hpp>
#include <boost/polygon/point_data.hpp>
#include <boost/polygon/point_traits.hpp>
#include <boost/polygon/polygon.hpp>
#include <boost/polygon/polygon_90_with_holes_data.hpp>
#include <boost/polygon/rectangle_concept.hpp>
#include <boost/polygon/rectangle_data.hpp>
#include <boost/polygon/rectangle_traits.hpp>
#include <boost/polygon/segment_concept.hpp>
#include <boost/polygon/segment_data.hpp>
#include <boost/polygon/segment_traits.hpp>
#include <boost/polygon/voronoi.hpp>
#include <boost/polygon/voronoi_builder.hpp>
#include <boost/polygon/voronoi_diagram.hpp>
#include <boost/polygon/voronoi_geometry_type.hpp>

export module boost.polygon;

export import boost.config;

#include "gen_exports/polygon.inc"

