// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/pool/object_pool.hpp>
#include <boost/pool/pool_alloc.hpp>

export module boost.pool;

export import boost.assert;
export import boost.config;
export import boost.throw_exception;

#include "gen_exports/pool.inc"

