// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/process/cstring_ref.hpp>
#include <boost/process/ext/cmd.hpp>
#include <boost/process/ext/cwd.hpp>
#include <boost/process/ext/env.hpp>
#include <boost/process/ext/exe.hpp>
#include <boost/process/process_handle.hpp>
#include <boost/process/v1.hpp>
#include <boost/process/v1/async_pipe.hpp>
#include <boost/process/v1/exception.hpp>
#include <boost/process/v1/extend.hpp>
// M11 platform guard: v1/v2 windows launchers are Windows-only headers
// (boost/winapi basic_types.hpp #errors off-Windows); M9 winapi.cppm
// convention. POSIX face = platform-neutral + posix-self-guarded surface.
#if defined(_WIN32) || defined(__CYGWIN__)
#include <boost/process/v1/windows.hpp>
#include <boost/process/v2/windows/show_window.hpp>
#include <boost/process/v2/windows/with_logon_launcher.hpp>
#include <boost/process/v2/windows/with_token_launcher.hpp>
#include <boost/process/windows/as_user_launcher.hpp>
#include <boost/process/windows/creation_flags.hpp>
#include <boost/process/windows/default_launcher.hpp>
#include <boost/process/windows/show_window.hpp>
#include <boost/process/windows/with_logon_launcher.hpp>
#include <boost/process/windows/with_token_launcher.hpp>
#endif
// M11 platform guard (POSIX): the mingw snapshot's GMF reached the v2
// core (basic_process) and the launcher detail helpers only through the
// windows launcher chain; on POSIX include the cross-platform core and
// the posix default launcher explicitly so the shared-surface `using`
// lines resolve.
#if !defined(_WIN32) && !defined(__CYGWIN__)
#include <boost/process/v2/process.hpp>
#include <boost/process/v2/posix/default_launcher.hpp>
#endif

export module boost.process;

export import boost.asio;
export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.filesystem;
export import boost.iterator;
export import boost.system;
export import boost.type_traits;
export import boost.utility;
export import boost.winapi;

#include "gen_exports/process.inc"

