// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/program_options.hpp>
#include <boost/program_options/environment_iterator.hpp>
#include <boost/program_options/eof_iterator.hpp>

export module boost.program_options;

export import boost.any;
export import boost.core;
export import boost.iterator;

#include "gen_exports/program_options.inc"

