// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/property_map/compose_property_map.hpp>
#include <boost/property_map/dynamic_property_map.hpp>
#include <boost/property_map/function_property_map.hpp>
#include <boost/property_map/parallel/caching_property_map.hpp>
#include <boost/property_map/parallel/global_index_map.hpp>
#include <boost/property_map/parallel/local_property_map.hpp>
#include <boost/property_map/parallel/simple_trigger.hpp>
#include <boost/property_map/property_map_iterator.hpp>
#include <boost/property_map/shared_array_property_map.hpp>
#include <boost/property_map/transform_value_property_map.hpp>

export module boost.property_map;

export import boost.any;
export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.function;
export import boost.iterator;
export import boost.lexical_cast;
export import boost.smart_ptr;
export import boost.throw_exception;
export import boost.type_index;
export import boost.type_traits;
export import boost.utility;

#include "gen_exports/property_map.inc"

