// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/property_tree/info_parser.hpp>
#include <boost/property_tree/ini_parser.hpp>
#include <boost/property_tree/json_parser.hpp>
#include <boost/property_tree/ptree_serialization.hpp>
#include <boost/property_tree/xml_parser.hpp>

export module boost.property_tree;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.multi_index;
export import boost.optional;
export import boost.type_traits;

#include "gen_exports/property_tree.inc"

