// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/ptr_container/clone_allocator.hpp>
#include <boost/ptr_container/exception.hpp>
#include <boost/ptr_container/nullable.hpp>
#include <boost/ptr_container/ptr_container.hpp>
#include <boost/ptr_container/serialize_ptr_container.hpp>

export module boost.ptr_container;

export import boost.array;
export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.iterator;
export import boost.range;
export import boost.smart_ptr;
export import boost.type_traits;
export import boost.unordered;

#include "gen_exports/ptr_container.inc"

