// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/qvm.hpp>
#include <boost/qvm/operations.hpp>
#include <boost/qvm/quat_traits_array.hpp>

export module boost.qvm;

#include "gen_exports/qvm.inc"

