// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/random.hpp>
#include <boost/random/faure.hpp>
#include <boost/random/niederreiter_base2.hpp>
#include <boost/random/random_device.hpp>
#include <boost/random/sobol.hpp>

export module boost.random;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.dynamic_bitset;
export import boost.system;
export import boost.type_traits;

#include "gen_exports/random.inc"

