// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/rational.hpp>

export module boost.rational;

export import boost.type_traits;

#include "gen_exports/rational.inc"

