// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/ratio.hpp>
#include <boost/ratio/config.hpp>

export module boost.ratio;

#include "gen_exports/ratio.inc"

