// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/regex/concepts.hpp>
#include <boost/regex/pending/object_cache.hpp>
#include <boost/regex/pending/unicode_iterator.hpp>
#include <boost/regex/user.hpp>
#include <boost/regex/v5/cregex.hpp>
#include <boost/regex/v5/iterator_category.hpp>
#include <boost/regex/v5/iterator_traits.hpp>
#include <boost/regex/v5/perl_matcher_common.hpp>
#include <boost/regex/v5/perl_matcher_non_recursive.hpp>
#include <boost/regex/v5/regex_fwd.hpp>

export module boost.regex;

export import boost.type_traits;

#include "gen_exports/regex.inc"

