// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/safe_numerics/automatic.hpp>
#include <boost/safe_numerics/checked_default.hpp>
#include <boost/safe_numerics/checked_integer.hpp>
#include <boost/safe_numerics/checked_result.hpp>
#include <boost/safe_numerics/checked_result_operations.hpp>
#include <boost/safe_numerics/concept/exception_policy.hpp>
#include <boost/safe_numerics/concept/integer.hpp>
#include <boost/safe_numerics/concept/numeric.hpp>
#include <boost/safe_numerics/concept/promotion_policy.hpp>
#include <boost/safe_numerics/cpp.hpp>
#include <boost/safe_numerics/exception.hpp>
#include <boost/safe_numerics/exception_policies.hpp>
#include <boost/safe_numerics/interval.hpp>
#include <boost/safe_numerics/safe_base.hpp>
#include <boost/safe_numerics/safe_base_operations.hpp>
#include <boost/safe_numerics/safe_common.hpp>
#include <boost/safe_numerics/safe_compare.hpp>
#include <boost/safe_numerics/safe_integer.hpp>
#include <boost/safe_numerics/safe_integer_literal.hpp>
#include <boost/safe_numerics/safe_integer_range.hpp>
#include <boost/safe_numerics/utility.hpp>

export module boost.safe_numerics;

export import boost.config;
export import boost.core;
export import boost.integer;
export import boost.logic;
export import boost.mp11;
export import boost.type_traits;

#include "gen_exports/safe_numerics.inc"

