// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/scope_exit.hpp>

export module boost.scope_exit;

export import boost.core;
export import boost.type_traits;

#include "gen_exports/scope_exit.inc"

