// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/scope/defer.hpp>
#include <boost/scope/error_code_checker.hpp>
#include <boost/scope/scope_fail.hpp>
#include <boost/scope/scope_success.hpp>
#include <boost/scope/unique_fd.hpp>

export module boost.scope;

export import boost.core;

#include "gen_exports/scope.inc"

