// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/signals2.hpp>
#include <boost/signals2/trackable.hpp>

export module boost.signals2;

export import boost.assert;
export import boost.core;
export import boost.iterator;
export import boost.mp11;
export import boost.optional;
export import boost.smart_ptr;
export import boost.type_traits;

#include "gen_exports/signals2.inc"

