// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/sort/block_indirect_sort/blk_detail/constants.hpp>
#include <boost/sort/common/deque_cnc.hpp>
#include <boost/sort/common/file_vector.hpp>
#include <boost/sort/common/int_array.hpp>
#include <boost/sort/common/rearrange.hpp>
#include <boost/sort/common/scheduler.hpp>
#include <boost/sort/common/time_measure.hpp>
#include <boost/sort/insert_sort/insert_sort.hpp>
#include <boost/sort/sort.hpp>

export module boost.sort;

export import boost.type_traits;

#include "gen_exports/sort.inc"

