// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
// M4: BOOST_STACKTRACE_LINK 切到外链模式, 定义来自 libs/stacktrace/src/basic.cpp — 2026-08-11-m4-compiled-libs.md §3
#define BOOST_STACKTRACE_LINK
#include <boost/stacktrace.hpp>

export module boost.stacktrace;

#include "gen_exports/stacktrace.inc"

