// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/static_string.hpp>

export module boost.static_string;

export import boost.container_hash;
export import boost.core;

#include "gen_exports/static_string.inc"

