// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/statechart/asynchronous_state_machine.hpp>
#include <boost/statechart/custom_reaction.hpp>
#include <boost/statechart/deferral.hpp>
#include <boost/statechart/exception_translator.hpp>
#include <boost/statechart/history.hpp>
#include <boost/statechart/in_state_reaction.hpp>
#include <boost/statechart/state.hpp>
#include <boost/statechart/termination.hpp>
#include <boost/statechart/transition.hpp>

export module boost.statechart;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.smart_ptr;
export import boost.thread;
export import boost.throw_exception;
export import boost.type_traits;

#include "gen_exports/statechart.inc"

