// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/stl_interfaces/sequence_container_interface.hpp>
#include <boost/stl_interfaces/view_interface.hpp>

export module boost.stl_interfaces;

export import boost.assert;
export import boost.config;

#include "gen_exports/stl_interfaces.inc"

