// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/test/auto_unit_test.hpp>
#include <boost/test/data/dataset.hpp>
#include <boost/test/data/for_each_sample.hpp>
#include <boost/test/debug_config.hpp>
#include <boost/test/floating_point_comparison.hpp>
#include <boost/test/output/compiler_log_formatter.hpp>
#include <boost/test/output/junit_log_formatter.hpp>
#include <boost/test/output/plain_report_formatter.hpp>
#include <boost/test/output/xml_log_formatter.hpp>
#include <boost/test/output/xml_report_formatter.hpp>
#include <boost/test/output_test_stream.hpp>
#include <boost/test/parameterized_test.hpp>
#include <boost/test/predicate_result.hpp>
#include <boost/test/prg_exec_monitor.hpp>
#include <boost/test/progress_monitor.hpp>
#include <boost/test/results_collector.hpp>
#include <boost/test/test_case_template.hpp>
#include <boost/test/test_exec_monitor.hpp>
#include <boost/test/test_framework_init_observer.hpp>
#include <boost/test/tree/test_case_counter.hpp>
#include <boost/test/tree/traverse.hpp>
#include <boost/test/unit_test_monitor.hpp>
#include <boost/test/unit_test_parameters.hpp>
#include <boost/test/utils/iterator/token_iterator.hpp>
#include <boost/test/utils/nullstream.hpp>
#include <boost/test/utils/runtime/cla/parser.hpp>
#include <boost/test/utils/runtime/env/fetch.hpp>
#include <boost/test/utils/runtime/finalize.hpp>
#include <boost/test/utils/xml_printer.hpp>

export module boost.test;

export import boost.algorithm;
export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.function;
export import boost.iterator;
export import boost.smart_ptr;
export import boost.type_traits;
export import boost.utility;

#include "gen_exports/test.inc"

