// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/thread.hpp>
#include <boost/thread/caller_context.hpp>
#include <boost/thread/completion_latch.hpp>
#include <boost/thread/concurrent_queues/deque_adaptor.hpp>
#include <boost/thread/concurrent_queues/deque_views.hpp>
#include <boost/thread/concurrent_queues/queue_adaptor.hpp>
#include <boost/thread/concurrent_queues/queue_views.hpp>
#include <boost/thread/concurrent_queues/sync_deque.hpp>
#include <boost/thread/concurrent_queues/sync_timed_queue.hpp>
#include <boost/thread/condition.hpp>
#include <boost/thread/csbl/deque.hpp>
#include <boost/thread/csbl/list.hpp>
#include <boost/thread/csbl/memory.hpp>
#include <boost/thread/csbl/memory/shared_ptr.hpp>
#include <boost/thread/csbl/queue.hpp>
#include <boost/thread/executors/inline_executor.hpp>
#include <boost/thread/executors/loop_executor.hpp>
#include <boost/thread/executors/scheduled_thread_pool.hpp>
#include <boost/thread/executors/scheduler.hpp>
#include <boost/thread/executors/scheduling_adaptor.hpp>
#include <boost/thread/executors/serial_executor.hpp>
#include <boost/thread/executors/serial_executor_cont.hpp>
#include <boost/thread/executors/thread_executor.hpp>
#include <boost/thread/experimental/task_region.hpp>
#include <boost/thread/externally_locked_stream.hpp>
#include <boost/thread/latch.hpp>
#include <boost/thread/lockable_adapter.hpp>
#include <boost/thread/null_mutex.hpp>
#include <boost/thread/ostream_buffer.hpp>
#include <boost/thread/poly_shared_lockable_adapter.hpp>
#include <boost/thread/reverse_lock.hpp>
#include <boost/thread/sync_bounded_queue.hpp>
#include <boost/thread/sync_queue.hpp>
#include <boost/thread/synchronized_value.hpp>
#include <boost/thread/testable_mutex.hpp>
#include <boost/thread/thread_guard.hpp>
#include <boost/thread/thread_pool.hpp>
#include <boost/thread/user_scheduler.hpp>
#include <boost/thread/win32/mfc_thread_init.hpp>
#include <boost/thread/with_lock_guard.hpp>

export module boost.thread;

export import boost.chrono;
export import boost.core;
export import boost.io;
export import boost.optional;
export import boost.system;
export import boost.type_traits;

#include "gen_exports/thread.inc"

