// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/throw_exception.hpp>

export module boost.throw_exception;

export import boost.assert;
export import boost.config;

#include "gen_exports/throw_exception.inc"

