// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/tokenizer.hpp>

export module boost.tokenizer;

export import boost.assert;
export import boost.config;
export import boost.iterator;
export import boost.throw_exception;
export import boost.type_traits;

#include "gen_exports/tokenizer.inc"

