// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/type_erasure/any_cast.hpp>
#include <boost/type_erasure/dynamic_any_cast.hpp>
#include <boost/type_erasure/free.hpp>
#include <boost/type_erasure/is_empty.hpp>
#include <boost/type_erasure/iterator.hpp>
#include <boost/type_erasure/member.hpp>
#include <boost/type_erasure/register_binding.hpp>
#include <boost/type_erasure/same_type.hpp>
#include <boost/type_erasure/tuple.hpp>

export module boost.type_erasure;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.iterator;
export import boost.throw_exception;
export import boost.type_traits;
export import boost.utility;

#include "gen_exports/type_erasure.inc"

