// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/type_index/runtime_cast.hpp>
#include <boost/type_index/runtime_cast/boost_shared_ptr_cast.hpp>
#include <boost/type_index/runtime_cast/std_shared_ptr_cast.hpp>

export module boost.type_index;

export import boost.assert;

#include "gen_exports/type_index.inc"

