// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/type_traits.hpp>
#include <boost/type_traits/alignment_traits.hpp>
#include <boost/type_traits/arithmetic_traits.hpp>
#include <boost/type_traits/array_traits.hpp>
#include <boost/type_traits/broken_compiler_spec.hpp>
#include <boost/type_traits/composite_traits.hpp>
#include <boost/type_traits/config.hpp>
#include <boost/type_traits/conversion_traits.hpp>
#include <boost/type_traits/cv_traits.hpp>
#include <boost/type_traits/detected_or.hpp>
#include <boost/type_traits/has_operator.hpp>
#include <boost/type_traits/ice.hpp>
#include <boost/type_traits/is_base_of_tr1.hpp>
#include <boost/type_traits/is_bounded_array.hpp>
#include <boost/type_traits/is_detected.hpp>
#include <boost/type_traits/is_detected_convertible.hpp>
#include <boost/type_traits/is_detected_exact.hpp>
#include <boost/type_traits/is_unbounded_array.hpp>
#include <boost/type_traits/object_traits.hpp>
#include <boost/type_traits/reference_traits.hpp>
#include <boost/type_traits/same_traits.hpp>
#include <boost/type_traits/transform_traits.hpp>

export module boost.type_traits;

#include "gen_exports/type_traits.inc"

