// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/units/base_units/angle/arcminute.hpp>
#include <boost/units/base_units/angle/arcsecond.hpp>
#include <boost/units/base_units/astronomical/astronomical_unit.hpp>
#include <boost/units/base_units/astronomical/light_day.hpp>
#include <boost/units/base_units/astronomical/light_hour.hpp>
#include <boost/units/base_units/astronomical/light_minute.hpp>
#include <boost/units/base_units/astronomical/light_year.hpp>
#include <boost/units/base_units/astronomical/parsec.hpp>
#include <boost/units/base_units/imperial/conversions.hpp>
#include <boost/units/base_units/imperial/drachm.hpp>
#include <boost/units/base_units/imperial/fluid_ounce.hpp>
#include <boost/units/base_units/imperial/foot.hpp>
#include <boost/units/base_units/imperial/furlong.hpp>
#include <boost/units/base_units/imperial/gallon.hpp>
#include <boost/units/base_units/imperial/gill.hpp>
#include <boost/units/base_units/imperial/grain.hpp>
#include <boost/units/base_units/imperial/hundredweight.hpp>
#include <boost/units/base_units/imperial/inch.hpp>
#include <boost/units/base_units/imperial/league.hpp>
#include <boost/units/base_units/imperial/mile.hpp>
#include <boost/units/base_units/imperial/ounce.hpp>
#include <boost/units/base_units/imperial/quart.hpp>
#include <boost/units/base_units/imperial/quarter.hpp>
#include <boost/units/base_units/imperial/stone.hpp>
#include <boost/units/base_units/imperial/thou.hpp>
#include <boost/units/base_units/imperial/ton.hpp>
#include <boost/units/base_units/metric/angstrom.hpp>
#include <boost/units/base_units/metric/are.hpp>
#include <boost/units/base_units/metric/atmosphere.hpp>
#include <boost/units/base_units/metric/bar.hpp>
#include <boost/units/base_units/metric/barn.hpp>
#include <boost/units/base_units/metric/day.hpp>
#include <boost/units/base_units/metric/fermi.hpp>
#include <boost/units/base_units/metric/hectare.hpp>
#include <boost/units/base_units/metric/hour.hpp>
#include <boost/units/base_units/metric/knot.hpp>
#include <boost/units/base_units/metric/liter.hpp>
#include <boost/units/base_units/metric/micron.hpp>
#include <boost/units/base_units/metric/minute.hpp>
#include <boost/units/base_units/metric/mmHg.hpp>
#include <boost/units/base_units/metric/nautical_mile.hpp>
#include <boost/units/base_units/metric/ton.hpp>
#include <boost/units/base_units/metric/torr.hpp>
#include <boost/units/base_units/metric/year.hpp>
#include <boost/units/base_units/us/cup.hpp>
#include <boost/units/base_units/us/dram.hpp>
#include <boost/units/base_units/us/fluid_dram.hpp>
#include <boost/units/base_units/us/fluid_ounce.hpp>
#include <boost/units/base_units/us/foot.hpp>
#include <boost/units/base_units/us/gallon.hpp>
#include <boost/units/base_units/us/gill.hpp>
#include <boost/units/base_units/us/grain.hpp>
#include <boost/units/base_units/us/hundredweight.hpp>
#include <boost/units/base_units/us/inch.hpp>
#include <boost/units/base_units/us/mil.hpp>
#include <boost/units/base_units/us/mile.hpp>
#include <boost/units/base_units/us/minim.hpp>
#include <boost/units/base_units/us/ounce.hpp>
#include <boost/units/base_units/us/pound_force.hpp>
#include <boost/units/base_units/us/quart.hpp>
#include <boost/units/base_units/us/tablespoon.hpp>
#include <boost/units/base_units/us/teaspoon.hpp>
#include <boost/units/base_units/us/ton.hpp>
#include <boost/units/cmath.hpp>
#include <boost/units/get_dimension.hpp>
#include <boost/units/get_system.hpp>
#include <boost/units/is_dim.hpp>
#include <boost/units/is_dimensionless.hpp>
#include <boost/units/is_dimensionless_quantity.hpp>
#include <boost/units/is_dimensionless_unit.hpp>
#include <boost/units/is_quantity.hpp>
#include <boost/units/is_quantity_of_system.hpp>
#include <boost/units/is_unit.hpp>
#include <boost/units/lambda.hpp>
#include <boost/units/limits.hpp>
#include <boost/units/physical_dimensions.hpp>
#include <boost/units/systems/abstract.hpp>
#include <boost/units/systems/angle/degrees.hpp>
#include <boost/units/systems/angle/gradians.hpp>
#include <boost/units/systems/angle/revolutions.hpp>
#include <boost/units/systems/cgs/io.hpp>
#include <boost/units/systems/information.hpp>
#include <boost/units/systems/si/codata/atomic-nuclear_constants.hpp>
#include <boost/units/systems/si/codata/physico-chemical_constants.hpp>
#include <boost/units/systems/si/codata_constants.hpp>
#include <boost/units/systems/si/io.hpp>
#include <boost/units/systems/si/prefixes.hpp>
#include <boost/units/systems/temperature/celsius.hpp>
#include <boost/units/systems/temperature/fahrenheit.hpp>

export module boost.units;

export import boost.assert;
export import boost.config;
export import boost.iterator;
export import boost.math;
export import boost.tuple;
export import boost.type_traits;
export import boost.utility;

#include "gen_exports/units.inc"

