// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/url.hpp>

export module boost.url;

export import boost.core;
export import boost.mp11;
export import boost.system;
export import boost.variant2;

#include "gen_exports/url.inc"

