// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/compressed_pair.hpp>
#include <boost/utility.hpp>
#include <boost/utility/addressof.hpp>
#include <boost/utility/compare_pointees.hpp>
#include <boost/utility/declval.hpp>
#include <boost/utility/explicit_operator_bool.hpp>
#include <boost/utility/in_place_factory.hpp>
#include <boost/utility/result_of.hpp>
// M11: string_ref.hpp curated out of the GMF — its buffer_fill enum
// mismatches between the boost.io/boost.utility BMIs on gcc 16.1;
// consumers include the deprecated header themselves.
#include <boost/utility/string_view.hpp>
#include <boost/utility/swap.hpp>
#include <boost/utility/typed_in_place_factory.hpp>
#include <boost/utility/value_init.hpp>

export module boost.utility;

export import boost.assert;
export import boost.config;
export import boost.core;
export import boost.io;
export import boost.throw_exception;
export import boost.type_traits;

#include "gen_exports/utility.inc"

