// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/uuid.hpp>
#include <boost/uuid/basic_name_generator.hpp>
#include <boost/uuid/entropy_error.hpp>
#include <boost/uuid/invalid_uuid.hpp>
#include <boost/uuid/uuid_generators.hpp>
#include <boost/uuid/uuid_hash.hpp>
#include <boost/uuid/uuid_serialize.hpp>

export module boost.uuid;

export import boost.assert;
export import boost.config;

#include "gen_exports/uuid.inc"

