// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/variant.hpp>
#include <boost/variant/multivisitors.hpp>
#include <boost/variant/polymorphic_get.hpp>

export module boost.variant;

export import boost.core;
export import boost.type_traits;

#include "gen_exports/variant.inc"

