// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/wave.hpp>
#include <boost/wave/cpplexer/cpp_lex_iterator.hpp>
#include <boost/wave/cpplexer/re2clex/cpp_re2c_lexer.hpp>
#include <boost/wave/grammars/cpp_chlit_grammar.hpp>
#include <boost/wave/grammars/cpp_defined_grammar.hpp>
#include <boost/wave/grammars/cpp_expression_grammar.hpp>
#include <boost/wave/grammars/cpp_grammar.hpp>
#include <boost/wave/grammars/cpp_has_include_grammar.hpp>
#include <boost/wave/grammars/cpp_intlit_grammar.hpp>
#include <boost/wave/grammars/cpp_predef_macros_grammar.hpp>

export module boost.wave;

export import boost.assert;
export import boost.concept_check;
export import boost.config;
export import boost.core;
export import boost.filesystem;
export import boost.iterator;
export import boost.multi_index;
export import boost.optional;
export import boost.pool;
export import boost.smart_ptr;
export import boost.thread;
export import boost.throw_exception;
export import boost.type_traits;
export import boost.utility;

#include "gen_exports/wave.inc"

