// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/winapi/bcrypt.hpp>
#include <boost/winapi/character_code_conversion.hpp>
#include <boost/winapi/crypt.hpp>
#include <boost/winapi/dbghelp.hpp>
#include <boost/winapi/debugapi.hpp>
#include <boost/winapi/directory_management.hpp>
#include <boost/winapi/dll.hpp>
#include <boost/winapi/environment.hpp>
#include <boost/winapi/error_codes.hpp>
#include <boost/winapi/error_handling.hpp>
#include <boost/winapi/file_management.hpp>
#include <boost/winapi/file_mapping.hpp>
#include <boost/winapi/get_process_times.hpp>
#include <boost/winapi/get_thread_times.hpp>
#include <boost/winapi/handle_info.hpp>
#include <boost/winapi/handles.hpp>
#include <boost/winapi/jobs.hpp>
#include <boost/winapi/memory.hpp>
#include <boost/winapi/page_protection_flags.hpp>
#include <boost/winapi/pipes.hpp>
#include <boost/winapi/priority_class.hpp>
#include <boost/winapi/process.hpp>
#include <boost/winapi/security.hpp>
#include <boost/winapi/shell.hpp>
#include <boost/winapi/show_window.hpp>
#include <boost/winapi/stack_backtrace.hpp>
#include <boost/winapi/synchronization.hpp>
#include <boost/winapi/system.hpp>
#include <boost/winapi/thread.hpp>
#include <boost/winapi/thread_pool.hpp>
#include <boost/winapi/timers.hpp>
#include <boost/winapi/tls.hpp>
#include <boost/winapi/waitable_timer.hpp>

export module boost.winapi;

#include "gen_exports/winapi.inc"

