// GENERATED by scripts/gen_exports.py — DO NOT EDIT (draft; M3 owns final form)
module;
#include <boost/yap/print.hpp>
#include <boost/yap/yap.hpp>

export module boost.yap;

export import boost.assert;
export import boost.type_index;

#include "gen_exports/yap.inc"

